# Generated by Django 4.2.10 on 2024-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=200)),
                ('noOfPills', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
