# Generated by Django 4.2.10 on 2024-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='userID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
