# Generated by Django 4.2.10 on 2024-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='modeOfContact',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
