# Generated by Django 4.2.11 on 2024-03-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_modeofcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='planName',
            field=models.TextField(default=''),
        ),
    ]
