# Generated by Django 4.2.10 on 2024-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_alter_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
