# Generated by Django 4.2.10 on 2024-03-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_alter_medicine_medicinename_alter_plan_medicinenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='medicineNames',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, to='plans.medicine'),
        ),
    ]
