# Generated by Django 4.2.10 on 2024-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_alter_plan_medicinenames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='medicineNames',
        ),
        migrations.AddField(
            model_name='plan',
            name='medicineNames',
            field=models.ManyToManyField(blank='True', to='plans.medicine'),
        ),
    ]
