# Generated by Django 4.2.10 on 2024-03-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_remove_plan_medicinenames_plan_medicinenames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='noOfPills',
        ),
        migrations.AddField(
            model_name='medicine',
            name='noOfPills',
            field=models.IntegerField(default=0),
        ),
    ]
