# Generated by Django 4.2.10 on 2024-03-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0020_remove_plan_medicinenames_plan_medicinenames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='medicineNames',
        ),
        migrations.CreateModel(
            name='PlanMedicineRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.medicine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'unique_together': {('plan', 'medicine')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='medicineNames',
            field=models.ManyToManyField(through='plans.PlanMedicineRelationship', to='plans.medicine'),
        ),
    ]
