# Generated by Django 4.2.10 on 2024-03-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0021_remove_plan_medicinenames_planmedicinerelationship_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planmedicinerelationship',
            unique_together=set(),
        ),
    ]
