# Generated by Django 4.2.10 on 2024-03-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0022_alter_planmedicinerelationship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planmedicinerelationship',
            unique_together={('plan', 'medicine')},
        ),
    ]
