# Generated by Django 4.2.10 on 2024-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0024_plan_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
