# Generated by Django 4.2.11 on 2024-03-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0026_medicine_date_created_alter_medicine_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('handle', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='telegramHandle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plans.validuser'),
        ),
    ]
