# Generated by Django 4.2.11 on 2024-03-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0027_validuser_plan_telegramhandle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='telegramHandle',
        ),
        migrations.DeleteModel(
            name='ValidUser',
        ),
    ]
