# Generated by Django 4.2.11 on 2024-03-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0029_plan_telegramhandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
