# Generated by Django 4.2.11 on 2024-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0030_plan_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegramHandle', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
