# Generated by Django 4.2.11 on 2024-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0031_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatID',
            field=models.IntegerField(default=0),
        ),
    ]
